"""
Vuln_VAS - Module 4: Reporting & Visualization Module
Input : Vulnerability analysis JSON from Module 3
Output: Streamlit dashboard + PDF report + HTML report + JSON export
"""

import json
import sys
import os
from datetime import datetime
from pathlib import Path

# ── third-party ──────────────────────────────
import streamlit as st
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from fpdf import FPDF

# ── local imports ─────────────────────────────
# Allow running standalone or imported from main.py
try:
    from vulnerability_analysis_module import analyze_services, save_analysis_report
except ImportError:
    pass


# ─────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────
SEVERITY_COLORS = {
    "Critical": "#e74c3c",
    "High"    : "#e67e22",
    "Medium"  : "#f1c40f",
    "Low"     : "#2ecc71",
    "Unknown" : "#95a5a6",
}

SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Unknown"]


# ─────────────────────────────────────────────
# PDF REPORT GENERATOR
# ─────────────────────────────────────────────
class VulnReport(FPDF):

    def header(self):
        self.set_fill_color(30, 30, 30)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(255, 255, 255)
        self.cell(0, 18, "Vuln_VAS  |  Security Assessment Report", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by Vuln_VAS  |  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(45, 45, 45)
        self.set_text_color(255, 255, 255)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.set_text_color(30, 30, 30)
        self.ln(2)

    def kv(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(80, 80, 80)
        self.cell(42, 6, key + ":", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 6, str(value))

    def severity_badge(self, sev: str):
        colors = {
            "Critical": (231, 76, 60),
            "High"    : (230, 126, 34),
            "Medium"  : (241, 196, 15),
            "Low"     : (46, 204, 113),
            "Unknown" : (149, 165, 166),
        }
        r, g, b = colors.get(sev, (149, 165, 166))
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 8)
        self.cell(22, 5, sev.upper(), align="C", fill=True, ln=False)
        self.set_text_color(30, 30, 30)


def generate_pdf(report: dict, output_path: str) -> str:
    pdf = VulnReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    target    = report.get("target", "N/A")
    scan_time = report.get("scan_time", "N/A")
    vulns     = report.get("vulnerabilities", [])
    risk      = report.get("risk_summary", {})

    # ── Cover info ───────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(30, 30, 30)
    pdf.ln(4)
    pdf.cell(0, 10, "Vulnerability Assessment Report", ln=True, align="C")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Target: {target}   |   Scanned: {scan_time}", ln=True, align="C")
    pdf.ln(6)

    # ── Risk Summary ─────────────────────────
    pdf.section_title("Risk Summary")
    pdf.set_font("Helvetica", "", 9)
    col_w = 38
    for sev in ["critical", "high", "medium", "low"]:
        count = risk.get(sev, 0)
        label = sev.capitalize()
        r, g, b = {
            "critical": (231, 76, 60),
            "high"    : (230, 126, 34),
            "medium"  : (241, 196, 15),
            "low"     : (46, 204, 113),
        }[sev]
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(col_w, 8, f"  {label}: {count}", fill=True, ln=False, border=0)
    pdf.ln(12)
    pdf.set_text_color(30, 30, 30)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, f"Overall Risk Score: {risk.get('overall_risk_score', 'N/A')} / 100", ln=True)
    pdf.ln(4)

    # ── Vulnerabilities ──────────────────────
    pdf.section_title(f"Vulnerabilities Detected ({len(vulns)})")
    pdf.ln(2)

    for i, v in enumerate(vulns, 1):
        if pdf.get_y() > 250:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(10, 6, f"{i}.", ln=False)
        pdf.cell(0, 6, f"{v['service']} {v['version']}  (Port {v['port']}/{v.get('proto','tcp')})", ln=False)
        pdf.ln(6)

        pdf.set_x(12)
        pdf.severity_badge(v.get("severity", "Unknown"))
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"   CVE: {v.get('cve','N/A')}   CVSS: {v.get('cvss_score', 0):.1f}   "
                       f"Exploit: {v.get('exploit_reference','None')}   Confidence: {v.get('confidence','N/A')}", ln=True)

        pdf.set_x(12)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 5, v.get("description", "")[:250])

        pdf.set_text_color(30, 30, 30)
        # Remediation hint
        pdf.set_x(12)
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(0, 102, 204)
        pdf.cell(0, 5, "Recommendation: " + get_recommendation(v), ln=True)
        pdf.set_text_color(30, 30, 30)
        pdf.ln(3)

    # ── Disclaimer ───────────────────────────
    pdf.add_page()
    pdf.section_title("Disclaimer")
    pdf.set_font("Helvetica", "", 9)
    pdf.multi_cell(0, 5,
        "This report was generated by Vuln_VAS for authorized security assessment only. "
        "All testing was performed with explicit consent on whitelisted targets. "
        "Unauthorized use of this tool or acting on its findings without proper authorization "
        "may violate applicable laws. The authors accept no liability for misuse."
    )

    pdf.output(output_path)
    return output_path


# ─────────────────────────────────────────────
# HTML REPORT GENERATOR
# ─────────────────────────────────────────────
def generate_html(report: dict, output_path: str) -> str:
    target    = report.get("target", "N/A")
    scan_time = report.get("scan_time", "N/A")
    vulns     = report.get("vulnerabilities", [])
    risk      = report.get("risk_summary", {})

    sev_badges = {
        "Critical": "background:#e74c3c",
        "High"    : "background:#e67e22",
        "Medium"  : "background:#f1c40f;color:#333",
        "Low"     : "background:#2ecc71",
        "Unknown" : "background:#95a5a6",
    }

    rows = ""
    for v in vulns:
        sev  = v.get("severity", "Unknown")
        rows += f"""
        <tr>
          <td>{v['service']} {v['version']}</td>
          <td>{v.get('port','N/A')}/{v.get('proto','tcp')}</td>
          <td><a href="https://nvd.nist.gov/vuln/detail/{v.get('cve','')}" target="_blank">{v.get('cve','N/A')}</a></td>
          <td>{v.get('cvss_score', 0):.1f}</td>
          <td><span class="badge" style="{sev_badges.get(sev, '')};padding:3px 8px;border-radius:4px;color:white;font-weight:bold">{sev}</span></td>
          <td>{v.get('exploit_reference','None')}</td>
          <td>{v.get('confidence','N/A')}</td>
          <td style="font-size:12px">{v.get('description','')[:120]}...</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Vuln_VAS Report – {target}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', sans-serif; background: #0f1117; color: #e0e0e0; padding: 24px; }}
  h1 {{ color: #e74c3c; font-size: 28px; margin-bottom: 4px; }}
  .meta {{ color: #888; font-size: 13px; margin-bottom: 24px; }}
  .cards {{ display: flex; gap: 16px; flex-wrap: wrap; margin-bottom: 28px; }}
  .card {{ background: #1a1d2e; border-radius: 10px; padding: 18px 28px; min-width: 130px; text-align: center; }}
  .card .num {{ font-size: 36px; font-weight: bold; }}
  .card .lbl {{ font-size: 12px; color: #aaa; margin-top: 4px; }}
  .crit {{ color: #e74c3c; }} .high {{ color: #e67e22; }}
  .med  {{ color: #f1c40f; }} .low  {{ color: #2ecc71; }}
  .score {{ color: #3498db; font-size: 22px; }}
  table {{ width: 100%; border-collapse: collapse; background: #1a1d2e; border-radius: 10px; overflow: hidden; }}
  th {{ background: #12141f; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; color: #888; }}
  td {{ padding: 9px 12px; border-bottom: 1px solid #222; font-size: 13px; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover {{ background: #1f2235; }}
  a {{ color: #5dade2; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .footer {{ text-align: center; color: #555; font-size: 12px; margin-top: 32px; }}
</style>
</head>
<body>
<h1>🔍 Vuln_VAS Security Report</h1>
<p class="meta">Target: <strong>{target}</strong> &nbsp;|&nbsp; Scan Time: {scan_time}</p>

<div class="cards">
  <div class="card"><div class="num crit">{risk.get('critical',0)}</div><div class="lbl">Critical</div></div>
  <div class="card"><div class="num high">{risk.get('high',0)}</div><div class="lbl">High</div></div>
  <div class="card"><div class="num med">{risk.get('medium',0)}</div><div class="lbl">Medium</div></div>
  <div class="card"><div class="num low">{risk.get('low',0)}</div><div class="lbl">Low</div></div>
  <div class="card"><div class="num" style="color:#3498db">{risk.get('overall_risk_score','N/A')}</div><div class="lbl">Risk Score /100</div></div>
  <div class="card"><div class="num" style="color:#9b59b6">{len(vulns)}</div><div class="lbl">Total Findings</div></div>
</div>

<table>
<thead>
  <tr>
    <th>Service / Version</th><th>Port</th><th>CVE</th><th>CVSS</th>
    <th>Severity</th><th>Exploit Ref</th><th>Confidence</th><th>Description</th>
  </tr>
</thead>
<tbody>{rows}</tbody>
</table>

<p class="footer">Generated by Vuln_VAS &nbsp;|&nbsp; For authorized use only</p>
</body>
</html>"""

    with open(output_path, "w") as f:
        f.write(html)
    return output_path


# ─────────────────────────────────────────────
# HELPER
# ─────────────────────────────────────────────
def get_recommendation(vuln: dict) -> str:
    sev = vuln.get("severity", "").lower()
    svc = vuln.get("service", "").lower()

    generic = {
        "critical": "Patch or disable this service immediately.",
        "high"    : "Update to the latest stable version and apply vendor patches.",
        "medium"  : "Review configuration and apply available security updates.",
        "low"     : "Monitor for further exposure and plan remediation.",
    }
    specific = {
        "vsftpd"  : "Upgrade vsftpd; consider disabling anonymous FTP access.",
        "openssh" : "Upgrade OpenSSH; enforce key-based auth, disable root login.",
        "apache"  : "Upgrade Apache httpd; disable directory listing; review .htaccess.",
        "mysql"   : "Upgrade MySQL; restrict remote root login; use strong credentials.",
        "samba"   : "Upgrade Samba; disable SMBv1; restrict share permissions.",
    }
    for key, rec in specific.items():
        if key in svc:
            return rec
    return generic.get(sev, "Consult vendor advisory for remediation steps.")


# ─────────────────────────────────────────────
# STREAMLIT DASHBOARD
# ─────────────────────────────────────────────
def run_dashboard():
    st.set_page_config(
        page_title="Vuln_VAS Dashboard",
        page_icon="🛡️",
        layout="wide",
        initial_sidebar_state="expanded",
    )

    # ── Custom CSS ───────────────────────────
    st.markdown("""
    <style>
    .stApp { background-color: #0f1117; }
    .metric-card {
        background: #1a1d2e; border-radius: 12px;
        padding: 20px; text-align: center;
    }
    .stMetric label { color: #aaa !important; font-size: 12px; }
    .stMetric .css-1wivap2 { color: #e0e0e0 !important; }
    </style>
    """, unsafe_allow_html=True)

    # ── Sidebar ──────────────────────────────
    with st.sidebar:
        st.image("https://img.shields.io/badge/Vuln_VAS-v1.0-red?style=for-the-badge")
        st.markdown("### 🔧 Controls")

        uploaded = st.file_uploader(
            "Load Analysis JSON (Module 3 output)",
            type=["json"],
            help="Upload the JSON file produced by vulnerability_analysis_module.py"
        )
        st.markdown("---")
        st.markdown("**Modules**")
        st.markdown("✅ Module 1 – Reconnaissance")
        st.markdown("✅ Module 2 – Data Parsing")
        st.markdown("✅ Module 3 – Vulnerability Analysis")
        st.markdown("✅ Module 4 – Reporting *(active)*")

    # ── Load data ────────────────────────────
    report = None
    if uploaded:
        report = json.load(uploaded)
    else:
        # Try default files in current dir
        candidates = sorted(Path(".").glob("vuln_analysis_*.json"), key=os.path.getmtime, reverse=True)
        if candidates:
            with open(candidates[0]) as f:
                report = json.load(f)
            st.sidebar.success(f"Loaded: {candidates[0].name}")

    if report is None:
        st.title("🛡️ Vuln_VAS – Vulnerability Assessment Dashboard")
        st.info("Upload a Module 3 JSON output file using the sidebar to view results.")
        st.stop()

    # ── Header ───────────────────────────────
    target    = report.get("target", "N/A")
    scan_time = report.get("scan_time", "N/A")
    vulns     = report.get("vulnerabilities", [])
    risk      = report.get("risk_summary", {})

    st.title(f"🛡️ Vuln_VAS  |  {target}")
    st.caption(f"Scan time: {scan_time}   |   Services analysed: {report.get('total_services', len(vulns))}")
    st.divider()

    # ── KPI Row ──────────────────────────────
    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("🔴 Critical", risk.get("critical", 0))
    c2.metric("🟠 High",     risk.get("high",     0))
    c3.metric("🟡 Medium",   risk.get("medium",   0))
    c4.metric("🟢 Low",      risk.get("low",      0))
    c5.metric("📊 Risk Score", f"{risk.get('overall_risk_score', 0)}/100")
    c6.metric("🎯 Total Vulns", len(vulns))

    st.divider()

    # ── Charts Row ───────────────────────────
    col_pie, col_cvss = st.columns(2)

    with col_pie:
        st.subheader("Severity Distribution")
        labels = [s for s in SEVERITY_ORDER if risk.get(s.lower(), 0) > 0]
        values = [risk.get(s.lower(), 0) for s in labels]
        colors = [SEVERITY_COLORS[s] for s in labels]
        if values:
            fig_pie = go.Figure(go.Pie(
                labels=labels, values=values,
                marker_colors=colors,
                hole=0.45,
                textinfo="label+percent"
            ))
            fig_pie.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                font_color="#e0e0e0", showlegend=False, margin=dict(t=10, b=10)
            )
            st.plotly_chart(fig_pie, use_container_width=True)

    with col_cvss:
        st.subheader("CVSS Scores by Service")
        if vulns:
            df_chart = pd.DataFrame([{
                "Service"   : f"{v['service']} {v['version']}",
                "CVSS"      : v.get("cvss_score", 0),
                "Severity"  : v.get("severity", "Unknown"),
            } for v in vulns])
            fig_bar = px.bar(
                df_chart.sort_values("CVSS", ascending=True),
                x="CVSS", y="Service", orientation="h",
                color="Severity",
                color_discrete_map=SEVERITY_COLORS,
                range_x=[0, 10],
            )
            fig_bar.update_layout(
                paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                font_color="#e0e0e0", margin=dict(t=10, b=10),
                yaxis=dict(tickfont=dict(size=11)),
            )
            st.plotly_chart(fig_bar, use_container_width=True)

    st.divider()

    # ── Vulnerability Table ───────────────────
    st.subheader("📋 Vulnerability Details")

    sev_filter = st.multiselect(
        "Filter by Severity",
        options=SEVERITY_ORDER,
        default=SEVERITY_ORDER,
    )

    if vulns:
        df = pd.DataFrame([{
            "Service"        : v.get("service", ""),
            "Version"        : v.get("version", ""),
            "Port"           : v.get("port", ""),
            "CVE"            : v.get("cve", "N/A"),
            "CVSS"           : v.get("cvss_score", 0),
            "Severity"       : v.get("severity", "Unknown"),
            "Exploit Ref"    : v.get("exploit_reference", "None"),
            "Confidence"     : v.get("confidence", "N/A"),
            "Description"    : v.get("description", "")[:120],
        } for v in vulns if v.get("severity", "Unknown") in sev_filter])

        st.dataframe(
            df,
            use_container_width=True,
            height=350,
            column_config={
                "CVSS"    : st.column_config.NumberColumn(format="%.1f"),
                "Severity": st.column_config.TextColumn(),
            }
        )

    st.divider()

    # ── Per-vuln Expanders ───────────────────
    st.subheader("🔍 Detailed Findings")
    for v in vulns:
        sev  = v.get("severity", "Unknown")
        icon = {"Critical": "🔴", "High": "🟠", "Medium": "🟡", "Low": "🟢"}.get(sev, "⚪")
        with st.expander(f"{icon} {v['service']} {v['version']}  —  {v.get('cve','N/A')}  (CVSS {v.get('cvss_score',0):.1f})"):
            r1, r2, r3 = st.columns(3)
            r1.markdown(f"**Port:** {v.get('port','N/A')}/{v.get('proto','tcp')}")
            r2.markdown(f"**Exploit Ref:** {v.get('exploit_reference','None')}")
            r3.markdown(f"**Confidence:** {v.get('confidence','N/A')}")

            st.markdown(f"**Description:** {v.get('description','')}")
            st.markdown(f"**All CVEs:** {', '.join(v.get('all_cves', [v.get('cve','N/A')]))}")

            if v.get("exploits"):
                st.markdown("**Exploit-DB Matches:**")
                for ex in v["exploits"]:
                    st.markdown(f"- `EDB-{ex.get('edb_id','N/A')}` — {ex.get('title','')}")

            st.info(f"💡 **Recommendation:** {get_recommendation(v)}")

    st.divider()

    # ── Export Buttons ───────────────────────
    st.subheader("📥 Export Reports")
    col_pdf, col_html, col_json = st.columns(3)

    target_clean = target.replace(".", "_")

    with col_pdf:
        if st.button("🖨️ Generate PDF Report", use_container_width=True):
            pdf_path = f"/tmp/vuln_report_{target_clean}.pdf"
            generate_pdf(report, pdf_path)
            with open(pdf_path, "rb") as f:
                st.download_button(
                    label="⬇️ Download PDF",
                    data=f.read(),
                    file_name=f"vuln_report_{target_clean}.pdf",
                    mime="application/pdf",
                    use_container_width=True,
                )

    with col_html:
        if st.button("🌐 Generate HTML Report", use_container_width=True):
            html_path = f"/tmp/vuln_report_{target_clean}.html"
            generate_html(report, html_path)
            with open(html_path, "r") as f:
                st.download_button(
                    label="⬇️ Download HTML",
                    data=f.read(),
                    file_name=f"vuln_report_{target_clean}.html",
                    mime="text/html",
                    use_container_width=True,
                )

    with col_json:
        st.download_button(
            label="⬇️ Download JSON",
            data=json.dumps(report, indent=4),
            file_name=f"vuln_analysis_{target_clean}.json",
            mime="application/json",
            use_container_width=True,
        )


# ─────────────────────────────────────────────
# STANDALONE EXPORT (no Streamlit)
# ─────────────────────────────────────────────
def export_reports(report: dict, output_dir: str = "."):
    """Generate PDF + HTML + JSON from a report dict without Streamlit."""
    Path(output_dir).mkdir(parents=True, exist_ok=True)
    target_clean = report.get("target", "target").replace(".", "_")

    pdf_path  = str(Path(output_dir) / f"vuln_report_{target_clean}.pdf")
    html_path = str(Path(output_dir) / f"vuln_report_{target_clean}.html")
    json_path = str(Path(output_dir) / f"vuln_analysis_{target_clean}.json")

    generate_pdf(report,  pdf_path)
    generate_html(report, html_path)
    with open(json_path, "w") as f:
        json.dump(report, f, indent=4)

    print(f"[✓] PDF  → {pdf_path}")
    print(f"[✓] HTML → {html_path}")
    print(f"[✓] JSON → {json_path}")
    return pdf_path, html_path, json_path


# ─────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────
if __name__ == "__main__":
    # If launched via `streamlit run reporting_module.py` → dashboard
    # If launched via `python reporting_module.py report.json` → export only
    if "streamlit" in sys.modules or "--" not in " ".join(sys.argv):
        # Streamlit context
        run_dashboard()
    else:
        if len(sys.argv) < 2:
            print("Usage: python reporting_module.py <analysis_report.json> [output_dir]")
            sys.exit(1)
        with open(sys.argv[1]) as f:
            report = json.load(f)
        out_dir = sys.argv[2] if len(sys.argv) > 2 else "reports"
        export_reports(report, out_dir)
